//********************************
//  アチーブメント用
//********************************

### アチーブメントマスタと達成状況取得
GET http://localhost:8000/api/achievements?user_id=1
Accept: application/json

### アチーブメント達成状況更新
POST http://localhost:8000/api/users/achievements/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|tozIbA2o2thyyH6taiFsXeZuz3Ni6vof2DuXx0wF49078daf

{
    "type": 1,
    "allie_val": 1
}

### アチーブメント報酬受け取り
POST http://localhost:8000/api/users/achievements/receive
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|tozIbA2o2thyyH6taiFsXeZuz3Ni6vof2DuXx0wF49078daf

{
    "achievement_id": 32
}
