//********************************
//  救難信号用
//********************************

### 救難信号に参加しているユーザーのプロフィール取得
GET http://localhost:8000/api/distress_signals/user/show?d_signal_id=1&user_id=1
Accept: application/json

### 募集した救難信号取得
GET http://localhost:8000/api/distress_signals/index?user_id=1
Accept: application/json

### 救難信号をランダムに取得
GET https://api-tikokukaihi.japaneast.cloudapp.azure.com/api/distress_signals/show?user_id=5
Accept: application/json

### 救難信号登録
POST http://localhost:8000/api/distress_signals/store
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|tozIbA2o2thyyH6taiFsXeZuz3Ni6vof2DuXx0wF49078daf

{
    "stage_id": 8
}

### 救難信号ゲームクリア
POST http://localhost:8000/api/distress_signals/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|tozIbA2o2thyyH6taiFsXeZuz3Ni6vof2DuXx0wF49078daf

{
    "d_signal_id": 1
}

### 救難信号削除
POST http://localhost:8000/api/distress_signals/destroy
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|tozIbA2o2thyyH6taiFsXeZuz3Ni6vof2DuXx0wF49078daf

{
    "d_signal_id": 3
}

### 参加ゲストの情報取得
GET http://localhost:8000/api/distress_signals/guest/show?d_signal_id=1
Accept: application/json

### ゲスト登録・配置情報更新
POST http://localhost:8000/api/distress_signals/guest/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|tozIbA2o2thyyH6taiFsXeZuz3Ni6vof2DuXx0wF49078dafs

{
    "d_signal_id": 4,
    "position": "TEST",
    "vector": "TEST"
}

### ゲスト削除
POST http://localhost:8000/api/distress_signals/guest/destroy
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|tozIbA2o2thyyH6taiFsXeZuz3Ni6vof2DuXx0wF49078daf

{
    "d_signal_id": 2,
    "destroy_user_id": 1
}

### リプレイ情報取得
GET http://localhost:8000/api/distress_signals/replay/show?d_signal_id=4
Accept: application/json

### リプレイ情報更新
POST http://localhost:8000/api/distress_signals/replay/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|tozIbA2o2thyyH6taiFsXeZuz3Ni6vof2DuXx0wF49078daf

{
    "d_signal_id": 4,
    "replay_data": "{(0,0,0)}"
}

### ホストのときの救難信号ログ取得
GET http://localhost:8000/api/distress_signals/host_log?user_id=1
Accept: application/json

### ゲストのときの救難信号ログ取得
GET http://localhost:8000/api/distress_signals/guest_log?user_id=1
Accept: application/json

### 救難信号の報酬受け取り
POST http://localhost:8000/api/distress_signals/reward/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|tozIbA2o2thyyH6taiFsXeZuz3Ni6vof2DuXx0wF49078daf

{
    "d_signal_id": 2
}
